Section "Device"
    Identifier "RPi5-Card1"
    Driver     "modesetting"
    Option     "kmsdev" "/dev/dri/card1"
EndSection

Section "Device"
    Identifier "Generic-Card0"
    Driver     "modesetting"
    Option     "kmsdev" "/dev/dri/card0"
EndSection

Section "Screen"
    Identifier "Screen1"
    Device     "RPi5-Card1"
EndSection

Section "Screen"
    Identifier "Screen0"
    Device     "Generic-Card0"
EndSection

Section "ServerLayout"
    Identifier "Default Layout"
    Screen 0 "Screen1"
    Screen 1 "Screen0"
EndSection
